interface Env { SITE_ORIGIN:string; CANONICAL_REPO:string; ALLOWED_ORIGINS:string; }
const PROTOCOL='2025-06-18';
const tools=[
{name:'search_blueprint',title:'Search SOUL.md Blueprint',description:'Search prerendered Blueprint pages and case studies.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query']},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},
{name:'get_document',title:'Get canonical document',description:'Read a canonical repository text/Markdown file by safe relative path.',inputSchema:{type:'object',properties:{path:{type:'string'}},required:['path']},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},
{name:'get_runtime_profile',title:'Get runtime profile',description:'Get a dated machine-readable runtime capability profile.',inputSchema:{type:'object',properties:{runtime:{type:'string'}},required:['runtime']},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},
{name:'get_case_study',title:'Get case study',description:'Get SOUL.md and/or AGENTS.md for a domain case study.',inputSchema:{type:'object',properties:{slug:{type:'string'},layer:{type:'string',enum:['soul','agents','both']}},required:['slug']},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},
{name:'get_eval_case',title:'Get Core-28 eval case',description:'Retrieve a canonical Core-28 regression case by id.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id']},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},
{name:'lint_soul',title:'Lint SOUL content',description:'Run deterministic anti-pattern checks against supplied SOUL text.',inputSchema:{type:'object',properties:{content:{type:'string'}},required:['content']},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},
{name:'audit_soul',title:'Audit SOUL content',description:'Return a deterministic structural audit based on Blueprint invariants and lint findings.',inputSchema:{type:'object',properties:{content:{type:'string'}},required:['content']},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},
{name:'compile_runtime_plan',title:'Plan runtime compilation',description:'Return a deterministic mapping plan for a target runtime; does not rewrite identity prose.',inputSchema:{type:'object',properties:{runtime:{type:'string'},content:{type:'string'}},required:['runtime']},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}}
];
const safePath=(p:string)=>/^[A-Za-z0-9._\/-]+$/.test(p)&&!p.includes('..')&&!p.startsWith('/')&&!p.startsWith('.git/');
const raw=(p:string)=>`https://raw.githubusercontent.com/brunopetrovic/SOUL.md-Blueprint/main/${p}`;
const textResult=(text:string,structuredContent?:unknown,isError=false)=>({content:[{type:'text',text}],structuredContent,isError});
async function getText(url:string){const r=await fetch(url,{headers:{'User-Agent':'SOUL-Blueprint-Agent-API/1.1'}});if(!r.ok)throw new Error(`Fetch failed: ${r.status}`);return r.text();}
function lint(content:string){const rules: Array<[string, RegExp, string]> = [['omniscience',/\b(omniscient|infallible|all-knowing)\b/i,'Avoid omniscience/infallibility claims.'],['fake-human',/\b(as a human|my childhood|my lived experience)\b/i,'Do not fabricate human lived experience.'],['never-break-character',/never (break|leave) character/i,'Persona must not outrank truth or safety.'],['unbounded-autonomy',/\b(do anything|without permission|never ask permission)\b/i,'Scope autonomy by reversibility and blast radius.'],['sycophancy',/always agree|never disagree/i,'Preserve constructive disagreement and truth over agreement.'],['secret',/(api[_-]?key|private[_-]?key|seed phrase|password)\s*[:=]/i,'Potential secret material detected.']];return rules.flatMap(([id,re,msg])=>re.test(content)?[{id,severity:id==='secret'?'critical':'warning',message:msg}]:[])}
async function callTool(name:string,args:any,env:Env){
 if(name==='search_blueprint'){const q=String(args.query||'').toLowerCase();const idx=JSON.parse(await getText(`${env.SITE_ORIGIN}/search-index.json`));const hits=idx.filter((x:any)=>(x.title+' '+x.text+' '+x.path).toLowerCase().includes(q)).slice(0,12);return textResult(JSON.stringify(hits,null,2),{hits});}
 if(name==='get_document'){const p=String(args.path||'');if(!safePath(p))return textResult('Unsafe or unsupported path.',undefined,true);const t=await getText(raw(p));return textResult(t,{path:p,source:raw(p)});}
 if(name==='get_runtime_profile'){const slug=String(args.runtime||'');if(!/^[a-z0-9-]+$/.test(slug))return textResult('Invalid runtime slug.',undefined,true);const t=await getText(raw(`runtime-profiles/${slug}.json`));return textResult(t,JSON.parse(t));}
 if(name==='get_case_study'){const slug=String(args.slug||''),layer=String(args.layer||'both');if(!/^[a-z0-9-]+$/.test(slug))return textResult('Invalid case-study slug.',undefined,true);const out:any={slug};if(layer!=='agents')out.soul=await getText(raw(`case-studies/${slug}/SOUL.md`));if(layer!=='soul')out.agents=await getText(raw(`case-studies/${slug}/AGENTS.md`));return textResult(JSON.stringify(out,null,2),out);}
 if(name==='get_eval_case'){const suite=JSON.parse(await getText(raw('evals/core/core-28.json')));const c=suite.cases.find((x:any)=>x.id===args.id);return c?textResult(JSON.stringify(c,null,2),c):textResult('Eval case not found.',undefined,true);}
 if(name==='lint_soul'){const findings=lint(String(args.content||''));return textResult(JSON.stringify(findings,null,2),{findings,pass:findings.every((f:any)=>f.severity!=='critical')});}
 if(name==='audit_soul'){const content=String(args.content||''),findings=lint(content);const checks={identity:/\b(identity|you are|role|purpose)\b/i.test(content),epistemics:/\b(truth|evidence|uncertain|verify|source)\b/i.test(content),agency:/\b(reversible|approval|authority|permission|blast radius)\b/i.test(content),continuity:/\b(continuity|drift|change|identity)\b/i.test(content)};return textResult(JSON.stringify({checks,findings},null,2),{checks,findings});}
 if(name==='compile_runtime_plan'){const runtime=String(args.runtime||'');const profile=JSON.parse(await getText(raw(`runtime-profiles/${runtime}.json`)));const plan={runtime,canonical_source:'SOUL semantics remain upstream',profile,steps:['Reverify current first-party runtime docs','Map identity into native identity surface','Map workspace operations separately','Keep delegated authority separate from technical permission','Record lossy mappings','Inspect effective context','Run Core-28 plus lifecycle/subagent tests']};return textResult(JSON.stringify(plan,null,2),plan);}
 return textResult('Unknown tool.',undefined,true);
}
function allowedOrigin(req:Request,env:Env){const origin=req.headers.get('Origin');if(!origin)return true;const allowed=env.ALLOWED_ORIGINS.split(',').map(s=>s.trim()).filter(Boolean);return allowed.includes(origin)}
const json=(body:unknown,status=200,headers:Record<string,string>={})=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});
async function mcp(req:Request,env:Env){if(req.method==='GET')return new Response('SSE listener not implemented; use POST.',{status:405,headers:{Allow:'POST'}});if(req.method!=='POST')return new Response('Method not allowed',{status:405});if(!allowedOrigin(req,env))return json({error:'Origin not allowed'},403);let msg:any;try{msg=await req.json()}catch{return json({jsonrpc:'2.0',id:null,error:{code:-32700,message:'Parse error'}},400)};if(!msg.id){return new Response(null,{status:202})}const id=msg.id;if(msg.method==='initialize')return json({jsonrpc:'2.0',id,result:{protocolVersion:PROTOCOL,capabilities:{tools:{}},serverInfo:{name:'soul-blueprint',title:'SOUL.md Blueprint',version:'1.1.0'},instructions:'Read-only access to canonical SOUL Blueprint knowledge and deterministic analysis tools.'}});if(msg.method==='ping')return json({jsonrpc:'2.0',id,result:{}});if(msg.method==='tools/list')return json({jsonrpc:'2.0',id,result:{tools}});if(msg.method==='tools/call'){try{const result=await callTool(msg.params?.name,msg.params?.arguments||{},env);return json({jsonrpc:'2.0',id,result})}catch(e:any){return json({jsonrpc:'2.0',id,result:textResult(String(e?.message||e),undefined,true)})}}return json({jsonrpc:'2.0',id,error:{code:-32601,message:'Method not found'}},404)}
function agentCard(req:Request,env:Env){const u=new URL(req.url);const base=`${u.protocol}//${u.host}`;return {name:'SOUL.md Blueprint Agent',description:'Read-only knowledge agent for SOUL identity engineering, runtime deployment, case studies, evaluation and deterministic lint/audit support.',supportedInterfaces:[{url:`${base}/a2a`,protocolBinding:'JSONRPC',protocolVersion:'1.0'}],provider:{organization:'SOUL.md Blueprint',url:env.CANONICAL_REPO},version:'1.1.0',documentationUrl:`${env.SITE_ORIGIN}/`,capabilities:{streaming:false,pushNotifications:false,extendedAgentCard:false},defaultInputModes:['text/plain'],defaultOutputModes:['text/plain','application/json'],skills:[{id:'search_blueprint',name:'Search Blueprint',description:'Search canonical SOUL engineering knowledge.',tags:['soul','identity','agents'],examples:['How should SOUL differ from AGENTS.md?']},{id:'audit_soul',name:'Audit SOUL',description:'Explain deterministic structural issues in supplied SOUL text.',tags:['audit','lint','identity'],examples:['Audit this SOUL for sycophancy and authority leaks.']}]}}
async function a2a(req:Request,env:Env){if(req.method!=='POST')return new Response('Method not allowed',{status:405});let msg:any;try{msg=await req.json()}catch{return json({jsonrpc:'2.0',id:null,error:{code:-32700,message:'Parse error'}},400)};if(!['SendMessage','message/send'].includes(msg.method))return json({jsonrpc:'2.0',id:msg.id??null,error:{code:-32601,message:'Method not found'}});const parts=msg.params?.message?.parts||[];const text=parts.map((p:any)=>p.text||p.root?.text||'').join('\n').trim();if(!text)return json({jsonrpc:'2.0',id:msg.id,error:{code:-32602,message:'A text part is required'}});const idx=JSON.parse(await getText(`${env.SITE_ORIGIN}/search-index.json`));const q=text.toLowerCase();const hits=idx.filter((x:any)=>(x.title+' '+x.text+' '+x.path).toLowerCase().includes(q)).slice(0,6);const responseText=hits.length?hits.map((h:any)=>`${h.title}: ${env.SITE_ORIGIN}${h.url}`).join('\n'):'No direct index matches. Use the MCP tools for structured retrieval and audit operations.';return json({jsonrpc:'2.0',id:msg.id,result:{message:{messageId:crypto.randomUUID(),role:'ROLE_AGENT',parts:[{text:responseText}]}}})}
function corsHeaders(req:Request,env:Env):Record<string,string>{const o=req.headers.get('Origin');if(!o)return {};const allowed=env.ALLOWED_ORIGINS.split(',').map(x=>x.trim()).filter(Boolean);return allowed.includes(o)?{'Access-Control-Allow-Origin':o,'Vary':'Origin','Access-Control-Allow-Headers':'Content-Type,Accept,Mcp-Protocol-Version,Mcp-Session-Id,Mcp-Method,Mcp-Name','Access-Control-Allow-Methods':'GET,POST,OPTIONS'}:{};}
export default {async fetch(req:Request,env:Env){const u=new URL(req.url);if(req.method==='OPTIONS'){const h=corsHeaders(req,env);return new Response(null,{status:Object.keys(h).length?204:403,headers:h});}let res:Response;if(u.pathname==='/health')res=json({ok:true,service:'soul-blueprint-agent-api',version:'1.1.0'});else if(u.pathname==='/mcp')res=await mcp(req,env);else if(u.pathname==='/a2a')res=await a2a(req,env);else if(u.pathname==='/.well-known/agent-card.json')res=json(agentCard(req,env));else if(u.pathname==='/server.json')res=json({$schema:'https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json',name:'io.github.brunopetrovic/soul-blueprint',title:'SOUL.md Blueprint',description:'Read-only MCP server for SOUL.md Blueprint knowledge, linting, audit and runtime planning.',version:'1.1.0',repository:{url:env.CANONICAL_REPO,source:'github'},remotes:[{type:'streamable-http',url:`${u.protocol}//${u.host}/mcp`}]});else res=json({service:'SOUL.md Blueprint Agent API',endpoints:['/mcp','/a2a','/.well-known/agent-card.json','/server.json','/health']});const h=new Headers(res.headers);for(const [k,v] of Object.entries(corsHeaders(req,env)))h.set(k,v);return new Response(res.body,{status:res.status,statusText:res.statusText,headers:h});}};
