import type { APIRoute } from 'astro';
import { runtimeSlugs, caseStudySlugs, titleize } from '../lib/content';

export const GET: APIRoute = ({ site }) => {
  const b = (site || new URL('https://soul-md-blueprint.pages.dev')).toString().replace(/\/$/, '');
  const text = `# SOUL.md Blueprint\n\n> Runtime-neutral specification and engineering discipline for durable AI-agent identity.\n\n## Canonical doctrine\n- [Master Blueprint](${b}/blueprint.md): Durable identity doctrine and engineering laws.\n- [Architecture](${b}/architecture.md): Semantic-layer separation and responsibility boundaries.\n- [Engineering Method](${b}/engineering.md): Construction, refactoring, compression, and verification method.\n- [Glossary](${b}/glossary.md): Canonical terminology used across the Blueprint.\n\n## Evaluation and specification\n- [Evaluation](${b}/evaluation.md): Behavioral regression methodology and Core-28.\n- [Specification](${b}/spec.md): Machine-readable schema index.\n- [Tooling](${b}/tooling.md): Reference linting and evaluation tooling.\n\n## Runtime deployment\n${runtimeSlugs.map(s => `- [${titleize(s)}](${b}/runtimes/${s}.md): Runtime capability profile and transport mapping.`).join('\n')}\n\n## Case studies\n${caseStudySlugs.map(s => `- [${titleize(s)}](${b}/case-studies/${s}.md): Applied SOUL.md and AGENTS.md pair.`).join('\n')}\n\n## Research and provenance\n- [Research](${b}/research.md): Empirical evidence, limitations, and synthesis.\n- [Sources](${b}/sources.md): Provenance and source-authority registry.\n- [Governance](${b}/governance.md): Repository operations, security, contribution, and change control.\n- [Repository](${b}/repository.md): Complete source-file index.\n\n## Agent discovery and representations\n- [Markdown sitemap](${b}/sitemap.md): Curated machine-readable site hierarchy.\n- [Repository AGENTS.md](${b}/AGENTS.md): Public repository operating instructions.\n- [Full corpus](${b}/llms-full.txt): Concatenated high-context AI corpus.\n- [Concise discovery](${b}/agents.txt): Minimal machine discovery notes.\n- [Wildcard agents.json](${b}/agents.json): Agent flow manifest linked to the real OpenAPI operations.\n- [OpenAPI](${b}/openapi.json): Read-only HTTP API contract.\n- [API Catalog](${b}/.well-known/api-catalog): RFC 9727 service discovery for the published read API.\n- [Catalog API](${b}/api/v1/catalog.json): Structured site, runtime, and case-study catalog.\n- [Agent permissions](${b}/.well-known/agent-permissions.json): LAS-WG v1.0.0 advisory interaction policy.\n- [Agent Skills index](${b}/.well-known/agent-skills/index.json): Discoverable skill manifest.\n- [SOUL Engineering Skill](${b}/.well-known/agent-skills/soul-engineering/SKILL.md): Reusable procedure for creating, auditing, compiling, and evaluating durable agent identity.\n- [XML sitemap](${b}/sitemap.xml): Crawler URL enumeration with stable source-aware lastmod values.\n- [GitHub repository](https://github.com/brunopetrovic/SOUL.md-Blueprint): Canonical source.\n`;
  return new Response(text, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'public, max-age=3600' }
  });
};
